const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

const GET_USER_REQUEST = 'GET_USER_REQUEST';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAILURE = 'GET_USER_FAILURE';

const GET_BUDGET_REQUEST = 'GET_BUDGET_REQUEST';
const GET_BUDGET_SUCCESS = 'GET_BUDGET_SUCCESS';
const GET_BUDGET_FAILURE = 'GET_BUDGET_FAILURE';
